services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=some-postgres'
      - 'POSTGRES_PASSWORD=mysecretpassword'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    networks:
      modulith-network:

  modulith-service:
    container_name: service
    image: modulith:1.0
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE:dev
    depends_on:
      - postgres

    networks:
      modulith-network:
    restart: unless-stopped
networks:
  modulith-network:
    driver: bridge