services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=some-postgres'
      - 'POSTGRES_PASSWORD=mysecretpassword'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
