apiVersion: v1
data:
  MODULITH_PASSWORD: mysecretpassword
  MODULITH_USERNAME: myuser
  MODULITH_HOST: "your ipv4"
  MODULITH_PORT: "5432"
  SPRING_PROFILE: docker
  MODULITH_DB_NAME: some-postgres
  DELETE_EVENT_DURATION: "4000"
  ACTUATOR_EXPOSED_ENDPOINTS: health, modulith
  SERVER_PORT: "9090"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: modulith
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: modulith-deployment
  name: modulith-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: modulith-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: modulith-deployment
    spec:
      containers:
        - image: anhnhadat/spring-modulith:1.0
          name: modulith
          ports:
            - containerPort: 9090
          envFrom:
            - configMapRef:
                name: modulith
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: modulith-deployment
  name: modulith-deployment
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
      nodePort: 32000
  selector:
    app: modulith-deployment
  type: NodePort
status:
  loadBalancer: {}