spring:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
  modulith:
    events:
      republish-outstanding-events-on-restart: false
#allow saving events to the table

delete:
  event:
    duration: 5000
management:
  endpoints:
    web:
      exposure:
        include: '*'
