name: build push image for deployment
on:
  push:
    branches:
      - main
env:
  job_env: ssss
jobs:
  sample-job-section:
    environment: action
    runs-on: ubuntu-latest
    env:
      SOME_DATA: some-data
    steps:
      - name: Print something
        run: echo "I am printing something"
      - name: Show host environment variables
        run: echo "some data ${{env.SOME_DATA}}actuator endpoints ${{vars.ACTUATOR_EXPOSED_ENDPOINTS}}"
      - name: print job env
        env:
          step_level_env: stepEnv
        run: echo "job env ${{env.job_env}}   step env ${{env.step_level_env}}"


  build-job-section:
    environment: action
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "23"
          cache: maven


  push-image-section:
    runs-on: ubuntu-latest
    steps:
      - name: print something
        run: echo "job env ${{env.job_env}}"


