name: build push image for deployment
on:
  push:
    branches:
      - main

jobs:
  build-section:
    environment: action
    runs-on: ubuntu-latest
    env:
      SOME_DATA: some-data
    steps:
      - name: Print something
        run: echo "I am printing something"
      - name: Show host environment variables
        run: echo "some data ${{env.SOME_DATA}}actuator endpoints ${{vars.ACTUATOR_EXPOSED_ENDPOINTS}}"



